### ISSUE TITLE
How can implement DB schema?

### ISSUE THREAD

**Issue by Vcarreon439** [ukushu/AkinatorEngine#2]
I already downloaded the System.Data.Sqlite dll, but I can't figure out how to connect a SQLite db with the project.

**Comment by ukushu** [comment]
SQLite must be injected as NuGet package - this is more easy than connect dll resource

Try to check how its implemented in "medAkinator" project inside of this repository

I cannot answer with more details as lot of time passed since I have wrote current repo :) 
Hope this will help you

**Comment by Vcarreon439** [comment]
I've successfully written the code to generate the database, but I'm struggling with how to operate the system. I would greatly appreciate any assistance you can provide.

**Comment by ukushu** [comment]
Check this code

https://github.com/ukushu/AkinatorEngine/tree/master/MedAkinator/Form1.cs

I believe there must be not too difficult to understand system

Or open MedAkinator project, create database file there and try to educate the system :)
